problem:
  num_nodes: 5
  depot_num: 0
  num_cars: 2
  cars_capacity: 100
  max_dis: 10
  min_dis: 1
  max_cap: 70
  min_cap: 1

GNN_input_embedding:
  node_dim: 1
  hidden_dim: 10
  output_dime: 6
  edge_dim: 1
  
graph_transformer:
  multi_head_attention:
    num_heads: 3
    model_dim: 6
  num_layers: 3
  ff_hidden_dim: 10

DQN:
  epsilon: 0.999
  epsilon_decay: 0.009
  rl: 3
  output_dim: 1
  hidden_dim: 10
  num_epoches: 100
  explore_model_update_step: 4
  target_model_update_step: 20
  replay_buff_cap: 4
  replay_buffer_first_size: 2
  discount: 0.9
  batch_size: 8

